### ISSUE TITLE
The schedule should show estimated datetime for execution

### ISSUE THREAD

**Issue by OysteinAmundsen** [OysteinAmundsen/gymsystems#13]
The datetime should be dynamic. Each item in the schedule should be set with a default time according to a configured execution time (default is 5 minutes). But the each items time should be pushed forward if the schedule is delayed for any reason. 

This depends on #14 and #39 

## Tasks

- [x] Tournaments should have a start time as well as a date. (Solved by #39)
- [x] Tournaments should set a duration per day, or an end time per day in order to divide the teams over the tournament duration (Solved by #39)
- [x] The scheduler and list-view should calculate start time ad-hoc. Starttime should not be saved.
- [ ] The list-view should display a countdown to the scheduled time for a participant
- [x] The starttime should be calculated using either last participants actual starttime, or tournaments starttime (if this is the first participant of the day)

**Comment by OysteinAmundsen** [comment]
This is good enough for this release. Closing this.
