### ISSUE TITLE
Teams can be marked as being in national classes OR teamgym

### ISSUE THREAD

**Issue by OysteinAmundsen** [OysteinAmundsen/gymsystems#29]
**National classes**
In the national classes, teams can compete in all disciplines or a selection of disciplines by their choosing. They will be judged in each discipline separately.
This is what is the current implementation

**TeamGym**
In this class, teams compete in all disciplines and will be judged on all disciplines collectively. 

## Tasks

Team-editor
- [x] Add a slider in team-editor marking either teamgym or national classes
- [x] When marked teamgym, all disciplines should be auto-checked.

Scheduler
- [x] Teams marked teamgym should be sorted last in the scheduler

Scoreboard/Display/Results
- [x] Do not calculate final score until all disciplines are done
- [x] Final score is the average of all disciplines

**Comment by OysteinAmundsen** [comment]
This is required for this version.
